### ISSUE TITLE
Error: Request failed with status code 429

### ISSUE THREAD

**Issue by jhemmmm** [Vinschers/google-drive-direct-video-url#1]
Hello,

First of all, the script is great but, I keep receiving an error 429 when I am running it on a dedicated server.

**Comment by Vinschers** [comment]
When the play_stream URL is accessed, the video player usually makes a lot of requests to get all the video chunks needed. There might be a limitation header in your server that is preventing the player to get all the information.
Have you tested the code on localhost?
